# Generated by Django 5.0.2 on 2024-05-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardusers',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
