# Generated by Django 5.0.2 on 2024-05-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidashboard', '0002_dashboardusers_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardusers',
            old_name='email_verified',
            new_name='is_active',
        ),
    ]
