# Generated by Django 5.0.2 on 2024-05-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtimeapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministatement',
            old_name='transaction_id',
            new_name='total_transactions',
        ),
    ]
